title: "Jekyll Actions Demo"
baseurl: /hammock
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-timeago
  - jekyll-handlebars
livereload: true
include:
  - _pages
