title: "Jekyll Actions Demo"
baseurl: /hammock
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-timeago
livereload: true
include:
  - _pages
  - _blogs
