Bliss



It feels weird writing this now that I'm home, especially since it's mostly for you parents who are currently in the same room as me, but I feel the memories of peru already slipping from my fingers as I try to grabs those wisps of recollection. It feels like attempting to scoop up water with a sieve when all I should be doing is plunging the sieve into the water, but that's getting harder and harder the longer I'm here.

But though I'm back, this story isn't finished yet so I'm doing my best to look back over my shoulder and articulate what I see.

Lockdown in lima was a weird little bubble of time: Peru itself was a bubble, somehow unfurling on a detached timeline of its own, away from the hustle and bustle of daily life, and here was a gift in the form of (an as yet unspecified amount of) time again removed from that to just Exist. After life on the move, constantly active seeing and doing and experiencing things (even if we did take a good few days of rest - but then again so did god) I unknowingly required time for being. At first, was certainly miffed about being stuck indoors in lima in midsummer; the prospect of two extra weeks in Peru would not have loomed so dark were we able still to travel within the country. Believe it or not, i've been here 6 months and Still not been everywhere i want to visit. But quickly we settled into lockdown life, becoming accustomed to the military patrols with their casual rifles and wearing a mask around the much shrunken market, only an echo of its former self. I nabbed myself a room in the house, strung up my jungle hammock, and accepted the new way of life.

The house, that blessed house, so big and dusty, somehow stuffy and airy simultaneously, where everyone (we were 5) had space to find peace and quiet if they wanted it. I could spend a whole day not seeing anyone, tucked away in my hammock or drawing or holding silent discos on the dancefloor with the giant inflatable and completely coincidental corona beer bottle (which J hosted a coronavirus party with just before lockdown) (what a man). But it was just as nice being with everyone, back together with Gem and Justino and even Chris who came from cusco to see us off and got trapped here too. With his cat. Poor thing.

So this was our life, cooking together, making flatbread, drinking beer up on the roof. The beautiful roof, saviour of lockdown, the sprawling view over lima carrying you just far enough to evade the claustrophobia knocking on the window. Might've encouraged some bad habits *cough* smoking *cough*, but we allowed ourselves the little escape from our desert island, adrift as the sun set over the urban ocean. Lima does host some stunning sunsets, when the churning chaos of the buildings gives way to the stark, undulating blanket of fairy lights stretching over the black Andean foothills. And then 8pm curfew hits, heralded nightly by someone blaring the national anthem loud enough to be heard across the Pacific. Who plays the (bloody long, but bloody great) national anthem, you might ask? None other than our lovely Justino of course, always providing the party to raucous cheers from his neighbours, and, eventually, the police. They weren't too thrilled at first, marrying their honking horns to our patriotic chorus, but after two weeks not even they could resist the searing pull of those lyrics, that marching band brass, the key changes.... yeah it's almost three minute long and every second is a joy to hear. Love that bloody anthem. Police weren't too thrilled about J trying to incite a salsa party afterwards, but you gotta take what you get.

We were exceedingly lucky to while away the lockdown in high-ceilinged comfort, not shut away in a hostel with strangers sharing rooms with 10 other people and devolving into Lord of the Flies with backpackers and instant noodles. Even our area was less strict and militarized; the military that pepper Chorrillos like Antony Gormley sculptures, however well-armed, are far outstripped by the toy soldier rows patrolling the centre of town. It was freaky leaving the house, illicitly purchasing beer through the bars of the shopfront which became harder and more fraught with fear the stricter alcohol regulations got, or once getting the bus alone which is something I prided myself in being good at in general, but made unsettling by the frosty interactions and crumbling ghost town around. G went a bit crazy being trapped in the house but (mama you will agree) I have an extraordinary capacity for doing absolutely nothing, and therefore it suited me quite well.

Chris and I set up a little drawing studio on the 3rd floor where I whiled away hour after hour, luxuriating in the time and state of relative restfulness. This whole trip has been excellent for my creativity, pushing me to work in a completely different manner to usual. On this trip, G and I have furiously scribbled away on snowing mountaintops, surreptitiously sketched in fancy government buildings, tried to draw in bumpy bus rides or swaying boats or surrounded by random people desperate to distract us at all costs (security guards get very bored....<3). Perched on some very precarious spots, in g's case more to get that perfect photo and in mine, well, let's just say there's a reason I fell through the roof. And always under time pressure! Always trying to finish before the sun sets, or the museum closes, the candle burns out or the rain gets too heavy for pencil to stick to paper (machu picchu lookin at u). Never sitting down to plan or develop, it was visceral, messy, utterly in-the-moment, a way of working I'm not accustomed to. Trying new materials, ways of drawing... I dislike a lot of what I drew, And a lot of it IS rushed and ugly, but there's bits of my sketchbook I'm so proud of.

Yeah quick detour there: it was therefore nice to come back to lima and proper sit down and spend TIME on drawings, filling in gaps that didn't quite get finished on hostel floors or waiting for the bus, drawing comics again, getting back a bit of the old mereida. Otherwise it was (MC) Hammock Time, letting our brains rot away to reruns of Friends or just lounging on the astroturf, increasing the yearning for Real Grass (and making your back really itchy). The only blight in Hotel Justino was the lil puppy, no longer really a puppy but strong enough to barge through many a blocked door and still ent-chew-siastic as ever. Bad pun, but she should be called Chewbacca not Nana.

So, there you go, how to survive lockdown in lima - all you really need is a hammock, an enormous inflatable coronabottle and speakers loud enough to give us all tinnitus. Oh wait.... nevermind.


From my hammock

(Yes it came back with me, what of it)

Mereida
