Aka The Jungle Blog

(Sending this from Cusco we're a bit behind)

It's been a chill month in the jungle. Put us on the spot and we could not tell you how we whiled away all that time, though there were a lot of hammocks involved... Didn't even have to leave the house to watch the birds and monkeys leaping between treetops squeaking, or walk far to visit the tarantula stationed as guard at the entrance to the reserve.

After several weeks of being pissed at blunt machetes, we discovered how to sharpen them - you run one blunt machete against another blunt machete, tadaa! We'd previously tried venturing straight into the jungle by the house but got about 15m before you could no longer move forwards, backwards or side to side. This forest is Dense. But finally succeeded in macheteing through on a solo mission to deforest the entire Amazon. Who needs cattle ranching or forest burning? Gemma and Mereida are On The Job. Seriously though it is impossible to move through this density of denseness without harming at least a few lil plants...

Disappointed as we've seen no snakes. Except in Low Belén where market meets water (district of Belén Market that gets seasonally flooded). While peering over the Venetian waters, speckled with small long boats and morning sunlight, to a church on stilts, we saw bobbing in a net a teeny fish and a long fucking venemous snake. Naturally, I Gemma, wanted to touch the snake. So with M holding my hand, I stretched my wellied foot into the river, creating a current until it floated over. It smelled dreadful, but curiously it felt empty. We squished and squashed it to the amusement of the locals who felt it necessary to tell us just how bad it smelled, though we very much knew this already.

After we lunched on the water (or in it, if we'd been one table further over) and I (G) dropped my fucking sketchbook in the fucking water. Book has yet to dry properly. At all!

We've seen more wildlife dead in the market than wild - Belén is scattered with the corpses of the coolest animals about. Skulls of jaguar, pelts of ocelot, skin's of snake. Heads of crocodile. Naturally we touched them all and both felt inclined to stretch our arms down the gullet of the crocodile. We were also both bathed in the rain of crocodile as the lady macheted the crocodile leg (arm? paw?) In half. We saw packaged up, but live, tortoises which come prepared in their own soup bowl. Anywhere and everywhere you can by anaconda wallets, jag tooth necklaces, none of this shit is even crafted with respect, its just a heartbreakign cash grab. The shock of seeing all this in one day made us need an extravagantly priced coffee that did  not quite wash away what we'd seen.

Now the central market of Iquitos, that's where its at. Donde esta la fiesta? Here. (Yes we know that's bad Spanish but it's too catchy). Mercado Central is littered with kittens and cats, sprawling among minimal vegetables, indulging (or suffering) the heat and heavy air that comes from being so far north. Iquitos is the world's largest city inaccessible by road - you gotta fly or boat it baby - but you wouldn't know it from the sheer volume of motorbikes and tricycles that cruise the behind streets. No person is too young, old, rich, poor or well dressed to hit the tarmac on a motorbike. The peril of holding your baby in one hand and your chickens in the other while riding that cloud of exhaust fumes in heels is unknown to the unhelmeted hordes of Iquitos.

Now us: we prefer the bus. Rainbow wooden buses with the Most ingenious window system (it's so clever!) populate the roads and are our way of getting from the concrete jungle of Iquitos to our real bit of jungle, 25km down the road (or further, if you add the distance travelled vertically when we bounce like buried babies over the desert paths). Loved the bus rides beyond anything, leaning out the window speeding south as city and pollution give way to forest and tree and sky. It's over an hour trek through village and farmland and forest from the road to the house, so we thought we were so deep in the jungle with nothing but insects for neighbours like true hippy dippy children of the forest. Until we looked it up on Google earth to find we're squished between two roads... there's still ample jungle to keep us satisfied though, and it's nice to know we're not too alone!

Did have almost a week to ourselves in the house, before that gave way to a rotating cast of other volunteers. The argentinians were mainly just difficult to understand because they pronounce 'll' and 'y' like 'shhh' (!!!?!?!?!) and the Australian dude was pretty quiet, but we had an absolute blast with a group of Germans. There was a couple, and another girl, and me all being German so poor Gem came all the way to the middle of the Amazon only to be surrounded by Germans. But she can now appreciate how stupid Germany is :) It was refreshingly fun to be around young Germans, a new perspective on the country and the culture and the politics, but they all took the absolute piss out of me for my slight Bavarianisms. They also taught us the Way of the Hammock - stringing up an illuminati triangle of hammocks and proceeded to complete every task imaginable while lying down and swinging slightly. We really did not do much in the jungle, mostly reading and reading and reading and I read two whole books in German (!) (Danke Barbara für mein lesematerial) and man it was relaxing. Awww we miss the Germans. Goddamn and god bless them! They were wonderful but then they left. We were very sad.

Right. Tomorrow it's off the Cusco, but we're writing this from the pool because after a month of slumming it in Cockroach Disneyland we deserve our lux. Every time we came into Iquitos we saw this hotel from the bus with a pool on it's sign so baby here we are, finally able to make the most of the tropical sun: alternately sizzling like bacon on the deckchair or boiling, like, well, boiled bacon? Boiled ham? in the pool. (I might be eating meat here but it's mostly chicken my ham knowledge is wanting).

Your soon-to-be-brown Amazonian Warrior Goddesses,

M + G
